<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script>
    //Cuando se concactenan mas de una callback para estar haciendo diferentes tareas que dependen de otras se empieza a generar el callbackhell 
    //para resolver esto se utilizan las promesas si se cumple: result | si falla: reject
    /* La promesa se puede apreciar como un if-else
    */

    //ya no necesitamos la funcion que pasamos como callback
    function cuadradoPromise(valor) {

      if (typeof valor !== "number") {
        return Promise.reject(`Error, el valor ${valor} no es un numero`);
      }
      return new Promise((resolve, reject) => {

        setTimeout(() => {
          resolve({
            valor,
            result: valor * valor
          }); //return positivo

        }, 0 | Math.random() * 1000);
      });
    }
    //.then() es el sig bloque que se ejecuta una vez se cumpla la funcion inicial (result)
    //se pueden tener los metodos then() que se necesiten
    //catch(): captura el error resultante del reject

    //funcion declarada arrow () =>
    cuadradoPromise(0).then(obj => {
      console.log("Inicia Promesa:");
      console.log(`Promise: ${obj.valor}, - ${obj.result}`);
      return cuadradoPromise(1).then(obj => {
        console.log(`Promise: ${obj.valor}, - ${obj.result}`);
        return cuadradoPromise(2).then(obj => {
          console.log(`Promise: ${obj.valor}, - ${obj.result}`);
          return cuadradoPromise("3").then(obj => {
            console.log(`Promise: ${obj.valor}, - ${obj.result}`);
            return cuadradoPromise(4).then(obj => {
              console.log(`Promise: ${obj.valor}, - ${obj.result}`);
              return cuadradoPromise(5).then(obj => {
                console.log(`Promise: ${obj.valor}, - ${obj.result}`);
                console.log("Fin Promise");
              })
            })
          })
        })
      })
    }).catch(err => console.error(err))

  </script>
</body>

</html>